//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspDotNetSummerProject.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_logs
    {
        public int activity_log_id { get; set; }
        public string activity_type { get; set; }
        public System.DateTime date { get; set; }
        public int user_id { get; set; }
    }
}
