//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspDotNetSummerProject.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int admin_id { get; set; }
        public string admin_name { get; set; }
        public System.DateTime dob { get; set; }
        public string address { get; set; }
        public int phone { get; set; }
        public string user_id { get; set; }
    }
}
