//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspDotNetSummerProject.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public int driver_id { get; set; }
        public string driver_name { get; set; }
        public System.DateTime dob { get; set; }
        public int phone { get; set; }
        public int license_no { get; set; }
        public int driver_nid { get; set; }
        public string vechile_no { get; set; }
        public string vechile_type { get; set; }
        public int user_id { get; set; }
        public int manger_id { get; set; }
        public string address { get; set; }
    }
}
