//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspDotNetSummerProject.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class labour_work_shedule
    {
        public int labour_work_s_id { get; set; }
        public string slot { get; set; }
        public string status { get; set; }
    }
}
