//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspDotNetSummerProject.Models.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AspdotNetSummerDBEntities : DbContext
    {
        public AspdotNetSummerDBEntities()
            : base("name=AspdotNetSummerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<driver> drivers { get; set; }
        public DbSet<labour_work_shedule> labour_work_shedule { get; set; }
        public DbSet<labour> labours { get; set; }
        public DbSet<manager> managers { get; set; }
        public DbSet<trip_operations> trip_operations { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<activity_logs> activity_logs { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<review> reviews { get; set; }
    }
}
